### ISSUE TITLE
rerun feeder lacking permissions to access the state db

### ISSUE THREAD

**Issue by jkeifer** [cirrus-geo/cirrus-geo#131]
Looks like I missed the required dynamo permissions for the rerun feeder when refactoring the permission out to each of the lambdas. I think we just need to add something like:

```
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:DescribeTable
      Resource:
        - !GetAtt StateTable.Arn
        - !Join ['', [!GetAtt StateTable.Arn, '/index/*']]
```
