### ISSUE TITLE
cirrus v0.7.0 batch task doesn't build

### ISSUE THREAD

**Issue by greyskyy** [cirrus-geo/cirrus-geo#154]
Using cirrus `v0.7.0` creating a batch task ends up creating an invalid cloudformation during cirrus build.

for example, running the following:

`$ cirrus create task --type batch foo foo`

creates the following job definition:
```yml
fooAsBatchJob:
  Type: "AWS::Batch::JobDefinition"
  Properties:
    JobDefinitionName: '#{AWS::StackName}-foo'
    Type: Container
    Parameters:
      url: ""
    ContainerProperties:
      Command:
        - run
        - ${self:service}-${self:provider.stage}-foo
        - Ref::url
      Environment: []
      Memory: 128
      Vcpus: 1
      Image: 'cirrusgeo/run-lambda:0.2.1'
      JobRoleArn: !Fn::GetAtt fooJobRole.Arn
    RetryStrategy:
      Attempts: 1
```

Note the `JobRoleArn` field.

After running `cirrus build`, the `.cirrus/serverless.yml` contains the following definition for `fooAsBatchJob`

```yml
fooAsBatchJob:
  Type: AWS::Batch::JobDefinition
  Properties:
    JobDefinitionName:
      Fn::Sub: ${AWS::StackName}-foo
    Type: Container
    Parameters:
      url: ''
    ContainerProperties:
      Command:
        - run
        - ${self:service}-${self:provider.stage}-foo
        - Ref::url
      Environment:
        # ...
      Memory: 128
      Vcpus: 1
      Image: cirrusgeo/run-lambda:0.2.1
      JobRoleArn:
        Fn::Fn::GetAtt: fooJobRole.Arn
    RetryStrategy:
      Attempts: 1
```

Note the `JobRoleArn` is now specified as `Fn:Fn:GetAtt`, which is an invalid function and causes a deployment failure.
