### ISSUE TITLE
`cirrus create task --type batch` creates yml that contains deprecated memory/cpu settings

### ISSUE THREAD

**Issue by stark525** [cirrus-geo/cirrus-geo#218]
When using the cirrus CLI to create a batch task, it will create yml that has deprecated resource settings:
```
            ContainerProperties:
              Command:
                - run
                - ${self:service}-${self:provider.stage}-hls-landsat
                - Ref::url
              Environment: []
              Memory: 32
              Vcpus: 2
```
Instead , it should generate `ResourceRequirements`:
```
            ContainerProperties:
              Command:
                - run
                - ${self:service}-${self:provider.stage}-hls-landsat
                - Ref::url
              Environment: []
              ResourceRequirements:
                - Type: VCPU
                  Value: 2
                - Type: MEMORY
                  Value: 31000
```
Ref: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html#cfn-batch-jobdefinition-containerproperties-memory
