### ISSUE TITLE
Evaluate if post-batch and publish tasks need permissive s3 permissions

### ISSUE THREAD

**Issue by philvarner** [cirrus-geo/cirrus-geo#262]
Some tasks have very permissive s3 grants, e.g.:

post-batch:

```yaml
   - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:GetBucketLocation"
      Resource: "*"
```

publish:
```yaml
- Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:GetBucketLocation"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource: "*"
```

Evaluate if these are necessary, or could be restricted. (It may not be possible to restrict them more without a mechanism for projects to add to them without completely copypasta'ing the entire task.)
